### PR TITLE
FIX: set Core OpenGL profile for OS X compat

### PR DESCRIPTION
**Pull request by ezpuzz**
this gets me a little closer to running on Yosemite, encountering another panic after this though.

i'm not sure at this point if it is due to using the core profile or what really.

I will post a backtrace in an issue and see if you can help me out.

### CODE REVIEW

**Comment by simias** [comment]
Thank you!

I've tried your patch and it doesn't seem to cause any regression on my computer, that being said I'd rather wait for the code to work completely on your computer before I merge those modifications.

Also the values for the `GLContextProfileMask` should be an enum instead of some magic value, if rust-sdl2 doesn't have it you should consider submitting a pull request there (I already did it for sdl2::video::GL_CONTEXT_DEBUG). After a quick look at the rust-sdl2 source code I found this enum which might be what you want: https://github.com/AngryLawyer/rust-sdl2/blob/master/src/sdl2/video.rs#L22-L30 (and its `to_gl_value` method).

Finally, and less importantly, I try to stick to 80 columns as much as possible in my code (I like splitting my editors in many vertical windows) so I'd prefer for the comment to be put above instead of at the end of the line (I find it more readable too).

**Comment by simias** [comment]
Is this modification still needed now that #4 is fixed?

**Comment by stykhomyrov** [comment]
@simias I believe that #4 and #3 are different problems. But in #8 I added line which sets current OpenGL profile to Core.

**Comment by simias** [comment]
Okay, brilliant.

**Pull request closed without merging**
